"""
Copyright (c) 2022, Lewis Chen
All rights reserved.

This source code is licensed under the MIT-style license found in the
LICENSE file in the root directory of this source tree. 
"""

def evenfibonacci():
    """
    Each new term in the Fibonacci sequence is generated by adding the 
    previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not 
    exceed four million, find the sum of the even-valued terms.
    """
    last_number = 4000000
    fibo = [1,2]
    for i in range(1, last_number):
        if i == fibo[-1] + fibo[-2]:
            fibo.append(i)
    print('fibo: ', fibo)
    a = 0
    for j in fibo:
        if j % 2 == 0:
            a += j
    print('a: ', a)
evenfibonacci()