"""empty message

Revision ID: 956daf07cb60
Revises: 3150bd4949f8
Create Date: 2023-05-05 13:10:21.334125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956daf07cb60'
down_revision = '3150bd4949f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
